// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProdutosApiWeb.Data;

namespace ProdutosApiWeb.Migrations
{
    [DbContext(typeof(ProdutoDbContext))]
    [Migration("20211028160556_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ProdutosApiWeb.Models.ProdutoModel", b =>
                {
                    b.Property<int>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estoque")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<decimal>("Preco")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdProduto");

                    b.ToTable("Produto");

                    b.HasData(
                        new
                        {
                            IdProduto = 1,
                            Cor = "Branco",
                            Estoque = 2,
                            Marca = "Apple",
                            Modelo = "Iphone 12 Pro",
                            Preco = 5600.00m
                        },
                        new
                        {
                            IdProduto = 2,
                            Cor = "Vermelho",
                            Estoque = 7,
                            Marca = "Apple",
                            Modelo = "Iphone 8",
                            Preco = 2600.00m
                        },
                        new
                        {
                            IdProduto = 3,
                            Cor = "Branco",
                            Estoque = 4,
                            Marca = "Apple",
                            Modelo = "Iphone X",
                            Preco = 3100.00m
                        },
                        new
                        {
                            IdProduto = 4,
                            Cor = "Preto",
                            Estoque = 1,
                            Marca = "Apple",
                            Modelo = "Iphone 11",
                            Preco = 4800.00m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
